ScreenManager:
    MenuScreen:
    SignupScreen:
    LoginScreen:
<MenuScreen>:
    name: "menu"
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "AutoBackup"
        MDLabel:

        MDScreen:

            MDBottomNavigation:

                MDBottomNavigationItem:
                    name: 'screen 1'
                    text: 'Photos'
                    icon: 'image'

                    MDLabel:
                        text: 'Photos'
                        halign: 'center'

                MDBottomNavigationItem:
                    name: 'screen 2'
                    text: 'Videos'
                    icon: 'video'


                    MDLabel:
                        text: 'Videos'
                        halign: 'center'

                MDBottomNavigationItem:
                    name: 'screen 3'
                    text: 'Audios'
                    icon: 'music'

                    MDLabel:
                        text: 'Audios'
                        halign: 'center'

                MDBottomNavigationItem:
                    name: 'screen 4'
                    text: 'Documents'
                    icon: 'file'

                    MDLabel:
                        text: 'Documents'
                        halign: 'center'

    MDRectangleFlatButton:
        text: "to Signup"
        pos_hint: {"center_x":0.5, "center_y": 0.5}
        on_press: root.manager.current= "signup"

<SignupScreen>:
    name: "signup"
    MDScreen:
        md_bg_color: [35/255, 59/255, 54/225, 1]
        MDCard:
            size_hint: None, None
            size: 320,400
            pos_hint: {"center_x":.5, "center_y":.5}
            elevation: 15
            md_bg_color: [35/225, 49/225, 48/229, 1]
            padding: 20
            spacing: 30
            orientation: "vertical"
            MDLabel:
                text: "SIGNUP"
                font_style: "Button"
                font_size: 45
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]
            MDTextField:
                hint_text: "Email"
                icon_right: "email"
                size_hint_x: None
                width: 220
                font_size: 20
                pos_hint: {"center_x":.5}
            MDTextField:
                hint_text: "Password"
                icon_right: "eye-off"
                size_hint_x: None
                width: 220
                font_size: 20
                pos_hint: {"center_x":.5}
            MDRoundFlatButton:
                text:"Signup"
                pos_hint: {"center_x":.5}
                font_size: 15
            MDTextButton:
                text: "Login"
                pos_hint: {"center_x":.8, "center_y":.2}
                on_press: root.manager.current = "login"


<LoginScreen>:
    name: "login"
    MDScreen:
        md_bg_color: [35/255, 59/255, 54/225, 1]
        MDCard:
            size_hint: None, None
            size: 320,400
            pos_hint: {"center_x":.5, "center_y":.5}
            elevation: 15
            md_bg_color: [35/225, 49/225, 48/229, 1]
            padding: 20
            spacing: 30
            orientation: "vertical"
            MDLabel:
                text: "LOGIN"
                font_style: "Button"
                font_size: 45
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]
            MDTextField:
                hint_text: "Email"
                icon_right: "email"
                size_hint_x: None
                width: 220
                font_size: 20
                pos_hint: {"center_x":.5}
            MDTextField:
                hint_text: "Password"
                icon_right: "eye-off"
                size_hint_x: None
                width: 220
                font_size: 20
                pos_hint: {"center_x":.5}
                password: True
            MDRoundFlatButton:
                text:"Login"
                pos_hint: {"center_x":.5}
                font_size: 15
            MDTextButton:
                text: "Create Account"
                pos_hint: {"center_x":.8, "center_y":.2}
                on_press: root.manager.current = "signup"





